### ISSUE TITLE
Set up GitHub Actions CI/CD for automated testing

### ISSUE THREAD

**Issue by LarsArtmann** [LarsArtmann/treefmt-full-flake#26]
## Overview
We need automated CI/CD to run template tests on every push and PR. This will catch formatter issues and regressions early.

### Basic CI Pipeline
- [ ] Run on push to main/master
- [ ] Run on all PRs
- [ ] Test all templates (minimal, default, complete)
- [ ] Support matrix testing across OS versions

### GitHub Actions Workflow
```yaml
name: CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-templates:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        template: [minimal, default, complete]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: treefmt-full-flake
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: ./tests/templates/test-${{ matrix.template }}.sh
```

### Additional Workflows
1. **Formatter Check**: Verify all formatters work
2. **Flake Check**: Run `nix flake check` on the main flake
3. **Documentation**: Build and verify docs
4. **Release**: Automated releases with changelogs

## Implementation Steps
1. Create `.github/workflows/ci.yml`
2. Set up Cachix for faster builds
3. Configure test matrix
4. Add status badges to README
5. Set up branch protection rules

## Cache Strategy
- Use Cachix for Nix store caching
- Cache formatter binaries
- Cache test dependencies
- Implement cache warming on schedule

## Success Metrics
- All tests pass in < 5 minutes
- Cache hit rate > 80%
- Zero flaky tests
- Clear error messages on failures

## Related Issues
- #22 - Cache invalidation issues
- #23 - Formatter inconsistencies
- #25 - Enhanced testing framework

## Benefits
- Catch regressions early
- Ensure cross-platform compatibility
- Automated testing reduces manual work
- Provides confidence for contributors
