### ISSUE TITLE
Add CI/CD generator for popular platforms

### ISSUE THREAD

**Issue by LarsArtmann** [LarsArtmann/treefmt-full-flake#3]
## Description
Automatically generate CI/CD configuration files for popular platforms to ensure consistent formatting across teams.

## Problem
Teams need formatting to run in CI to catch issues before merge, but setting up CI configs manually is error-prone and time-consuming.

## Proposed Solution
Add generators for popular CI platforms:

```bash
nix run .#generate-ci --type github-actions
nix run .#generate-ci --type gitlab-ci
nix run .#generate-ci --type circleci
```

## Implementation Details
- [ ] **GitHub Actions generator**
  - Creates `.github/workflows/format.yml`
  - Includes Nix caching with actions/cache
  - Supports both format check and auto-fix modes
  - Matrix builds for multiple systems if needed
- [ ] **GitLab CI generator**
  - Creates `.gitlab-ci.yml` formatting job
  - Uses GitLab's caching mechanisms
- [ ] **CircleCI generator**
  - Creates `.circleci/config.yml` formatting job
- [ ] **Generic shell script** for other platforms
- [ ] **Configuration options**:
  - `--check-only` (fail on formatting issues)
  - `--auto-fix` (commit fixes back)
  - `--cache` (enable/disable caching)
  - `--systems` (specify target systems)

## Example Generated GitHub Actions
```yaml
name: Format Check
on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: experimental-features = nix-command flakes
      - uses: actions/cache@v3
        with:
          path: ~/.cache/nix
          key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}
      - run: nix fmt -- --check
```

## Success Criteria
- One command generates working CI config
- Configs include proper caching for performance
- Support both check and auto-fix modes
- Clear documentation and examples

## Priority
🔥 **High** - Essential for team adoption

## Related Issues
None

## Labels
- enhancement
- ci/cd
- team-workflow
